spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres

logging:
  level:
    org.shipstone.demo.cache.zipcode: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
message:
  standard: "YEAH c'est trop cool"
server:
  port: 8090