spring:
  profiles:
    active: @spring.profiles.active@
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  # acces cache de type Redis
#  cache:
#    type: redis
#    redis:
#      time-to-live: 6000 # TTL global en ms
#      # les données de connexion au Redis propre à chaque env.
  # acces cache de type Redis

  # acces cache de type ehCache
  cache:
    jcache:
      config: classpath:ehcache3.xml
    type: jcache
  # acces cache de type ehCache

logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(%-37.37logger{32}){blue} %clr(:){red} %clr(%m){faint}%n%throwable}{FATAL=white, ERROR=red, WARN=blue, INFO=black, DEBUG=green, TRACE=blue}"
  level:
    root: ERROR
    org.shipstone.demo.cache.app: INFO
    org.springframework: WARN
    org.hibernate: WARN
server:
  servlet:
    context-path: "/api"
  port: 8080
