spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://app-db:5432/postgres

logging:
  level:
    root: ERROR
    org.shipstone.demo.cache.app: INFO
    org.springframework: ERROR
    org.hibernate: ERROR
    org.hibernate.SQL: DEBUG
app:
  server:
    ping: http://pingapp/api/
    zipcode: http://zipcode/api/