spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://app-db:5432/postgres
  # acces cache de type Redis
  redis:
    host: redis
    port: 6379
  # acces cache de type Redis

logging:
  level:
    root: ERROR
    org.shipstone.demo.cache.app: INFO
    org.springframework: ERROR
    org.hibernate: ERROR
    org.hibernate.SQL: DEBUG
app:
  server:
    ping: http://pingapp:8080/api/
    zipcode: http://zipcode:8080/api/