version: '3'
networks:
  cache_net:
    external: true
services:

  # reverse proxy
  nginx:
    container_name: nginx
    image: nginx:1.15.5
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    links:
      - pgadmin
      - pingapp
      - zipcode
      - app-1
      - app-2
    depends_on:
      - pgadmin
      - pingapp
      - zipcode
      - app-1
      - app-2
    networks:
      - cache_net
  # Applications
  app-1:
    build:
      ./app-app/
    image: shipstone/app:1.0
    container_name: app-1
    ports:
      - 8083:8080
    links:
      - pingapp
      - zipcode
      - app-db
    depends_on:
      - pingapp
      - zipcode
      - app-db
    networks:
      - cache_net
  app-2:
    build:
      ./app-app/
    image: shipstone/app:1.0
    container_name: app-2
    ports:
      - 8084:8080
    links:
      - pingapp
      - zipcode
      - app-db
    depends_on:
      - pingapp
      - zipcode
      - app-db
    networks:
      - cache_net
  pingapp:
    build:
      ./ping-app/
    image: shipstone/pingapp:1.0
    container_name: pingapp
    ports:
      - 8081:8080
    networks:
      - cache_net
  zipcode:
    build:
      ./zipcode-app/
    image: shipstone/zipcode:1.1
    container_name: zipcode
    ports:
      - 8082:8080
    networks:
      - cache_net
#  app-1:
#    build:
#      ./app-app/
#    image: shipstone/cache-demo-app:1.0
#    container_name: app-1.0-1
#    links:
#      - app-db
#    depends_on:
#      - app-db
#  app-2:
#    build:
#      ./app-app/
#   image: shipstone/cache-demo-app:1.0
#    container_name: app-1.0-2
#    links:
#      - app-db
#    depends_on:
#      - app-db


#  # pgAdmin
  pgadmin:
    image: fenglc/pgadmin4:2.1-python2.7-alpine
    container_name: pgadmin4
    links:
      - app-db:postgres
      - zipcode-db:postgres
    depends_on:
      - app-db
      - zipcode-db
    ports:
      - 5050:5050
    networks:
      - cache_net

  # Bases de donnée
  app-db:
    build:
      context: ./app-db/
    image: shipstone/app-db:1.0
    container_name: app-db
    ports:
      - 5432:5432
    networks:
      - cache_net
  zipcode-db:
    build:
      context: ./zipcode-db/
    image: shipstone/zipcode-db:1.1
    container_name: zipcode-db
    ports:
      - 5433:5432
    networks:
      - cache_net

  # Cache partagé
#  redis:
#    image: redis:5.0
#    container_name: redis
#    ports:
#      - 6379:6379

  ehcache:
    hostname: ehcache
    image: terracotta/terracotta-server-oss:5.5.1
    container_name: ehcache
    environment:
      - OFFHEAP_RESOURCE1_SIZE=256
      - OFFHEAP_RESOURCE1_UNIT=MB
      - OFFHEAP_RESOURCE1_NAME=primary-server-resource
    ports:
      - 9410:9410
    networks:
      - cache_net
