FROM openjdk:12-jdk-alpine
WORKDIR /root/
COPY  zipcode-1.1.1.jar /root/
# COPY glowroot/ /root/glowroot
# CMD java -javaagent:/root/glowroot/glowroot.jar  -jar zipcode-1.1.0.jar
CMD java -jar zipcode-1.1.1.jar
